name: Release

on: pull_request

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: macos-10-15
            name: macos
          - os: ubuntu-22.04
            name: linux-amd64
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - name: Run tests
        run: cargo test

      - name: Build Release
        run: |
          cargo build --release
          strip target/release/spr
          tar vczC target/release/ spr >spr-${{ github.sha }}-${{ matrix.name }}.tar.gz
          ls -lh spr-*.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: spr-*.tar.gz

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          prerelease: ${{ contains(github.ref, '-') }}
          files: |
            ./*/spr-*.tar.gz

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
